### ISSUE TITLE
Unnötige Scrollbars (in Firefox)

### ISSUE THREAD

**Issue by gnunicorn** [DemokratieInBewegung/portal#1]
In Firefox Nightly (`Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0`) zeigt mir der Browser scrollbalken rechts und unten mit minimalen Scrollbereich, aber ohne, dass es viel sinn ergibt. Scheinbar floatet da irgendwas aus dem sichtbaren Bereich (nen margin irgendwo?)

![screenshot wed mar 21 2018 13 25 21 gmt 0100 cet 3193x1569](https://user-images.githubusercontent.com/40496/37709802-a56c59a4-2d0b-11e8-89b1-782612513c96.png)

**Comment by michaelvoss82** [comment]
hatte ich schon in Commit https://github.com/DemokratieInBewegung/portal/commit/9c209799131430c5fae09d3f24148c0117124fc4 behoben
